structure(list(url = "https://api.twitter.com/1.1/statuses/update.json?status=this%20is%20a%20title%0Athis%20is%20a%20test%20tweet%20with%20an%20image%0AISO%20etc.%0A%23tag%20%23tag2&media_ids=1404105074402541569", 
    status_code = 200L, headers = structure(list(`cache-control` = "no-cache, no-store, must-revalidate, pre-check=0, post-check=0", 
        `content-disposition` = "attachment; filename=json.json", 
        `content-encoding` = "gzip", `content-length` = "1114", 
        `content-type` = "application/json;charset=utf-8", date = "Sun, 13 Jun 2021 15:55:11 GMT", 
        expires = "Tue, 31 Mar 1981 05:00:00 GMT", `last-modified` = "Sun, 13 Jun 2021 15:55:11 GMT", 
        pragma = "no-cache", server = "tsa_b", status = "200 OK", 
        `strict-transport-security` = "max-age=631138519", `x-access-level` = "read-write", 
        `x-connection-hash` = "aa71997d9f549b65b63255bbfe994202", 
        `x-content-type-options` = "nosniff", `x-frame-options` = "SAMEORIGIN", 
        `x-response-time` = "128", `x-transaction` = "0081011d008073b6", 
        `x-twitter-response-tags` = "BouncerCompliant", `x-xss-protection` = "0"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/2", 
        headers = structure(list(`cache-control` = "no-cache, no-store, must-revalidate, pre-check=0, post-check=0", 
            `content-disposition` = "attachment; filename=json.json", 
            `content-encoding` = "gzip", `content-length` = "1114", 
            `content-type` = "application/json;charset=utf-8", 
            date = "Sun, 13 Jun 2021 15:55:11 GMT", expires = "Tue, 31 Mar 1981 05:00:00 GMT", 
            `last-modified` = "Sun, 13 Jun 2021 15:55:11 GMT", 
            pragma = "no-cache", server = "tsa_b", status = "200 OK", 
            `strict-transport-security` = "max-age=631138519", 
            `x-access-level` = "read-write", `x-connection-hash` = "aa71997d9f549b65b63255bbfe994202", 
            `x-content-type-options` = "nosniff", `x-frame-options` = "SAMEORIGIN", 
            `x-response-time` = "128", `x-transaction` = "0081011d008073b6", 
            `x-twitter-response-tags` = "BouncerCompliant", `x-xss-protection` = "0"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = c(".twitter.com", 
    "api.twitter.com", ".twitter.com"), flag = c(TRUE, FALSE, 
    TRUE), path = c("/", "/", "/"), secure = c(TRUE, FALSE, TRUE
    ), expiration = structure(c(1686671503, Inf, 1686671503), class = c("POSIXct", 
    "POSIXt")), name = c("personalization_id", "lang", "guest_id"
    ), value = c("REDACTED", "REDACTED", "REDACTED")), row.names = c(NA, 
    -3L), class = "data.frame"), content = charToRaw("{\"created_at\":\"Sun Jun 13 15:55:11 +0000 2021\",\"id\":1404105076000579586,\"id_str\":\"1404105076000579586\",\"text\":\"this is a title\\nthis is a test tweet with an image\\nISO etc.\\n#tag #tag2 https:\\/\\/t.co\\/Yn88HkvcEr\",\"truncated\":false,\"entities\":{\"hashtags\":[{\"text\":\"tag\",\"indices\":[60,64]},{\"text\":\"tag2\",\"indices\":[65,70]}],\"symbols\":[],\"user_mentions\":[],\"urls\":[],\"media\":[{\"id\":1404105074402541569,\"id_str\":\"1404105074402541569\",\"indices\":[71,94],\"media_url\":\"http:\\/\\/pbs.twimg.com\\/media\\/E3xiIDsWQAEpqsY.jpg\",\"media_url_https\":\"https:\\/\\/pbs.twimg.com\\/media\\/E3xiIDsWQAEpqsY.jpg\",\"url\":\"https:\\/\\/t.co\\/Yn88HkvcEr\",\"display_url\":\"pic.twitter.com\\/Yn88HkvcEr\",\"expanded_url\":\"https:\\/\\/twitter.com\\/Temathesis\\/status\\/1404105076000579586\\/photo\\/1\",\"type\":\"photo\",\"sizes\":{\"medium\":{\"w\":200,\"h\":133,\"resize\":\"fit\"},\"small\":{\"w\":200,\"h\":133,\"resize\":\"fit\"},\"thumb\":{\"w\":133,\"h\":133,\"resize\":\"crop\"},\"large\":{\"w\":200,\"h\":133,\"resize\":\"fit\"}}}]},\"extended_entities\":{\"media\":[{\"id\":1404105074402541569,\"id_str\":\"1404105074402541569\",\"indices\":[71,94],\"media_url\":\"http:\\/\\/pbs.twimg.com\\/media\\/E3xiIDsWQAEpqsY.jpg\",\"media_url_https\":\"https:\\/\\/pbs.twimg.com\\/media\\/E3xiIDsWQAEpqsY.jpg\",\"url\":\"https:\\/\\/t.co\\/Yn88HkvcEr\",\"display_url\":\"pic.twitter.com\\/Yn88HkvcEr\",\"expanded_url\":\"https:\\/\\/twitter.com\\/Temathesis\\/status\\/1404105076000579586\\/photo\\/1\",\"type\":\"photo\",\"sizes\":{\"medium\":{\"w\":200,\"h\":133,\"resize\":\"fit\"},\"small\":{\"w\":200,\"h\":133,\"resize\":\"fit\"},\"thumb\":{\"w\":133,\"h\":133,\"resize\":\"crop\"},\"large\":{\"w\":200,\"h\":133,\"resize\":\"fit\"}}}]},\"source\":\"\\u003ca href=\\\"http:\\/\\/jonkeane.com\\\" rel=\\\"nofollow\\\"\\u003ephototweetr-meta\\u003c\\/a\\u003e\",\"in_reply_to_status_id\":null,\"in_reply_to_status_id_str\":null,\"in_reply_to_user_id\":null,\"in_reply_to_user_id_str\":null,\"in_reply_to_screen_name\":null,\"user\":{\"id\":2538370573,\"id_str\":\"2538370573\",\"name\":\"Metathesis\",\"screen_name\":\"Temathesis\",\"location\":\"\",\"description\":\"You're probably not interested.\",\"url\":null,\"entities\":{\"description\":{\"urls\":[]}},\"protected\":false,\"followers_count\":7,\"friends_count\":0,\"listed_count\":0,\"created_at\":\"Sat May 31 23:26:50 +0000 2014\",\"favourites_count\":0,\"utc_offset\":null,\"time_zone\":null,\"geo_enabled\":false,\"verified\":false,\"statuses_count\":665,\"lang\":null,\"contributors_enabled\":false,\"is_translator\":false,\"is_translation_enabled\":false,\"profile_background_color\":\"C0DEED\",\"profile_background_image_url\":\"http:\\/\\/abs.twimg.com\\/images\\/themes\\/theme1\\/bg.png\",\"profile_background_image_url_https\":\"https:\\/\\/abs.twimg.com\\/images\\/themes\\/theme1\\/bg.png\",\"profile_background_tile\":false,\"profile_image_url\":\"http:\\/\\/pbs.twimg.com\\/profile_images\\/472883170430300160\\/uCeStY73_normal.jpeg\",\"profile_image_url_https\":\"https:\\/\\/pbs.twimg.com\\/profile_images\\/472883170430300160\\/uCeStY73_normal.jpeg\",\"profile_link_color\":\"FFFFFF\",\"profile_sidebar_border_color\":\"C0DEED\",\"profile_sidebar_fill_color\":\"DDEEF6\",\"profile_text_color\":\"333333\",\"profile_use_background_image\":true,\"has_extended_profile\":false,\"default_profile\":false,\"default_profile_image\":false,\"following\":false,\"follow_request_sent\":false,\"notifications\":false,\"translator_type\":\"none\",\"withheld_in_countries\":[]},\"geo\":null,\"coordinates\":null,\"place\":null,\"contributors\":null,\"is_quote_status\":false,\"retweet_count\":0,\"favorite_count\":0,\"favorited\":false,\"retweeted\":false,\"possibly_sensitive\":false,\"lang\":\"en\"}"), 
    date = structure(1623599711, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.000047, 
    connect = 0.000049, pretransfer = 0.000204, starttransfer = 0.167936, 
    total = 0.168029)), class = "response")
