structure(list(url = "https://upload.twitter.com/1.1/media/metadata/create.json", 
    status_code = 200L, headers = structure(list(`cache-control` = "no-cache, no-store, must-revalidate, pre-check=0, post-check=0", 
        `content-length` = "0", `content-security-policy` = "default-src 'self'; connect-src 'self'; font-src 'self' https://*.twimg.com https://twitter.com https://ton.twitter.com data:; frame-src 'self' https://*.twimg.com https://twitter.com https://ton.twitter.com; img-src 'self' https://*.twimg.com https://twitter.com https://ton.twitter.com data:; media-src 'self' https://*.twimg.com https://twitter.com https://ton.twitter.com; object-src 'none'; script-src 'self' https://*.twimg.com https://twitter.com https://ton.twitter.com; style-src 'self' https://*.twimg.com https://twitter.com https://ton.twitter.com; report-uri https://twitter.com/i/csp_report?a=OBZG6ZTJNRSWE2LSMQ%3D%3D%3D%3D%3D%3D&ro=false;", 
        `content-type` = "text/html;charset=utf-8", date = "Sun, 13 Jun 2021 15:55:11 GMT", 
        expires = "Tue, 31 Mar 1981 05:00:00 GMT", `last-modified` = "Sun, 13 Jun 2021 15:55:11 GMT", 
        pragma = "no-cache", server = "tsa_b", status = "200 OK", 
        `strict-transport-security` = "max-age=631138519", `timing-allow-origin` = "https://twitter.com, https://mobile.twitter.com", 
        vary = "Origin", `x-access-level` = "read-write", `x-connection-hash` = "335b724d638fd53bf7959ad0450860e3", 
        `x-frame-options` = "SAMEORIGIN", `x-rate-limit-limit` = "2000", 
        `x-rate-limit-remaining` = "1997", `x-rate-limit-reset` = "1623602338", 
        `x-response-time` = "17", `x-transaction` = "00ad205e0054dc86", 
        `x-tsa-request-body-time` = "1", `x-twitter-response-tags` = "BouncerCompliant", 
        `x-xss-protection` = "1; mode=block"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/2", 
        headers = structure(list(`cache-control` = "no-cache, no-store, must-revalidate, pre-check=0, post-check=0", 
            `content-length` = "0", `content-security-policy` = "default-src 'self'; connect-src 'self'; font-src 'self' https://*.twimg.com https://twitter.com https://ton.twitter.com data:; frame-src 'self' https://*.twimg.com https://twitter.com https://ton.twitter.com; img-src 'self' https://*.twimg.com https://twitter.com https://ton.twitter.com data:; media-src 'self' https://*.twimg.com https://twitter.com https://ton.twitter.com; object-src 'none'; script-src 'self' https://*.twimg.com https://twitter.com https://ton.twitter.com; style-src 'self' https://*.twimg.com https://twitter.com https://ton.twitter.com; report-uri https://twitter.com/i/csp_report?a=OBZG6ZTJNRSWE2LSMQ%3D%3D%3D%3D%3D%3D&ro=false;", 
            `content-type` = "text/html;charset=utf-8", date = "Sun, 13 Jun 2021 15:55:11 GMT", 
            expires = "Tue, 31 Mar 1981 05:00:00 GMT", `last-modified` = "Sun, 13 Jun 2021 15:55:11 GMT", 
            pragma = "no-cache", server = "tsa_b", status = "200 OK", 
            `strict-transport-security` = "max-age=631138519", 
            `timing-allow-origin` = "https://twitter.com, https://mobile.twitter.com", 
            vary = "Origin", `x-access-level` = "read-write", 
            `x-connection-hash` = "335b724d638fd53bf7959ad0450860e3", 
            `x-frame-options` = "SAMEORIGIN", `x-rate-limit-limit` = "2000", 
            `x-rate-limit-remaining` = "1997", `x-rate-limit-reset` = "1623602338", 
            `x-response-time` = "17", `x-transaction` = "00ad205e0054dc86", 
            `x-tsa-request-body-time` = "1", `x-twitter-response-tags` = "BouncerCompliant", 
            `x-xss-protection` = "1; mode=block"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = c(".twitter.com", 
    "upload.twitter.com", ".twitter.com"), flag = c(TRUE, FALSE, 
    TRUE), path = c("/", "/", "/"), secure = c(TRUE, FALSE, TRUE
    ), expiration = structure(c(1686671483, Inf, 1686671483), class = c("POSIXct", 
    "POSIXt")), name = c("personalization_id", "lang", "guest_id"
    ), value = c("REDACTED", "REDACTED", "REDACTED")), row.names = c(NA, 
    -3L), class = "data.frame"), content = charToRaw(""), date = structure(1623599711, class = c("POSIXct", 
    "POSIXt"), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.000044, 
    connect = 0.000046, pretransfer = 0.000164, starttransfer = 0.000184, 
    total = 0.057233)), class = "response")
